//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitoysWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_Agent
    {
        public System.Guid ID { get; set; }
        public string CompanyName { get; set; }
        public string Area { get; set; }
        public string RegisteredAddress { get; set; }
        public string CorporateRepresentative { get; set; }
        public System.DateTime CompanyRegistrationTime { get; set; }
        public int CorporationNature { get; set; }
        public int MarketPersonnelNum { get; set; }
        public int SalerPersonnelNum { get; set; }
        public int AfterSalesPersonalNum { get; set; }
        public string ScopeBusiness { get; set; }
        public string SalesArea { get; set; }
        public string AnnualSales { get; set; }
        public string MainBusiness { get; set; }
        public string MainClientCategory { get; set; }
        public string Contact { get; set; }
        public string ContactMobilePhone { get; set; }
        public string EMail { get; set; }
        public string QQWeChat { get; set; }
        public string Tel { get; set; }
        public string FAX { get; set; }
        public string CompanyWebSite { get; set; }
        public bool IsAgentOtherProducts { get; set; }
        public string OtherProducts { get; set; }
        public string DevelopMarketAssumptions { get; set; }
        public string CompanyChannelsResources { get; set; }
        public string CooperationSuggestion { get; set; }
        public int Status { get; set; }
        public int CreateDate { get; set; }
    }
}
