//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitoysWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_AfterSales
    {
        public System.Guid ID { get; set; }
        public string AfterSalesNum { get; set; }
        public string MobilePhone { get; set; }
        public string Address { get; set; }
        public string ProblemDescr { get; set; }
        public int Status { get; set; }
        public string TrackingNO { get; set; }
        public int ProductModel { get; set; }
        public string ExpressCompany { get; set; }
        public int CreateDate { get; set; }
        public string Contact { get; set; }
        public string Pic1 { get; set; }
        public string Pic2 { get; set; }
        public string Pic3 { get; set; }
        public string Pic4 { get; set; }
        public string Pic5 { get; set; }
        public string AuditRemark { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
    }
}
