//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitoysWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_ContactUS
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string MailAddress { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public int CreateDate { get; set; }
        public int Status { get; set; }
        public string Remark { get; set; }
    }
}
